config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "flights#index"
  get "/flights", to: "flights#index"
  #get "/booking", to: "bookings#new"
  #post "/booking", to: "bookings#create"
  #get "/bookings", to: "bookings#show"
  resources :bookings, only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departing_flights, :foreign_key => :starting_airport_id, class_name: "Flight"
	has_many :arriving_flights, :foreign_key => :leaving_airport_id, class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :flight
	has_many :passengers
	accepts_nested_attributes_for :passengers

end

app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :starting_airport, class_name: "Airport"
	belongs_to :finishing_airport, class_name: "Airport"
	has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :print_date, :print_dates, :print_time
  	
  def print_dates(dates)
  	new_dates = []
  	dates.each do |date|
  		new_dates = print_date(date)
  	end
  end

  def print_date(date)
  	date.strftime("%m/%d/%Y")
  end

  def print_time(date)
  	date.strftime("%r")
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	def new
		@flight = Flight.find(params[:chosen_flight_id])
		@booking = @flight.bookings.build
		for i in 0...(params[:passengers].to_i)
			@message = "#{i}"
			@booking.passengers.build
		end
	end

	def create 
		@booking = Booking.create(flight_id: params[:booking][:flight_id])
		params[:booking][:passengers_attributes].each do |i|
			@booking.passengers.create(name: params[:booking][:passengers_attributes][i][:name], email: params[:booking][:passengers_attributes][i][:email])
			PassengerMailer.welcome_email(@booking.passengers.find_by(name: params[:booking][:passengers_attributes][i][:name])).deliver_now
		end
		redirect_to booking_path(@booking.id)
	end

	def show
		@booking = Booking.find(params[:id])
		@flight = @booking.flight
	end

	private

		def booking_params
	      params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
	    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def index
		#Airports
		init_airports
		#Dates
		@flights = Flight.all
		init_dates
		#search
		search_flights
	end

	def init_airports
		@airports = Airport.all
		@airport_codes = [] 
		@airports.each do |airport| 
			@airport_codes.push(airport.code) 
		end
	end

	def init_dates
		@dates = []
		@flights.each do |flight|
			if (!@dates.include?(print_date(flight.start_date_time)))
				@dates.push(print_date(flight.start_date_time))
			end
		end 
	end

	def search_flights
		if (params[:starting_airport] != nil)
			@searched_flights = []
			@airports.each do |airport|
				if (airport.code == params[:starting_airport])
					@start = airport
				end
				if (airport.code == params[:finishing_airport])
					@finish = airport
				end
			end
			@flights.each do |flight|
				if (flight.starting_airport_id == @start.id && flight.finishing_airport_id == @finish.id && print_date(flight.start_date_time) == params[:start_date_time])
					@searched_flights.push(flight)
				end
			end
		else
			@searched_flights = []
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h3> Flight Details </h3>
<h4>Departure: <%= @flight.starting_airport.code %> </h4>
<p>Date: <%= print_date(@flight.start_date_time) %> Time: <%= print_time(@flight.start_date_time) %></p>
<p>Duration: <%= @flight.duration_seconds %></p>
<h4>Arrival: <%= @flight.finishing_airport.code %> </h4>
<p>Date: <%= print_date(@flight.start_date_time + @flight.duration_seconds) %> Time: <%= print_time(@flight.start_date_time + @flight.duration_seconds) %></p>

<%= form_for(@booking, url: bookings_path) do |book|%>  	  
  	<%= book.fields_for :passengers do |pass| %>
   		<%= pass.label :name %>
  		<%= pass.text_field :name %> 	
  		<%= pass.label :email %>
  		<%= pass.text_field :email %>
  		<br>
  		<br> 	
  	<% end %> 
  <%= book.hidden_field :flight_id, :value => @flight.id %>
  <%= submit_tag "Submit" %>
<% end %>

<%= @message %>

app/views/bookings/show.html.erb
<h3> Flight Details </h3>
<h4>Departure: <%= @flight.starting_airport.code %> </h4>
<p>Date: <%= print_date(@flight.start_date_time) %> Time: <%= print_time(@flight.start_date_time) %></p>
<p>Duration: <%= @flight.duration_seconds %></p>
<h4>Arrival: <%= @flight.finishing_airport.code %> </h4>
<p>Date: <%= print_date(@flight.start_date_time + @flight.duration_seconds) %> Time: <%= print_time(@flight.start_date_time + @flight.duration_seconds) %></p>

<h3> Passenger Details </h3>
<% @booking.passengers.each do |passenger| %>
	<br> 
	<div style ="height: 100px; width: 200px; border:1px solid black">
		<p> Name: <%= passenger.name %> </p>
		<p> Email: <%= passenger.email %> </p>
	</div>
<% end %>

app/views/flights/index.html.erb
<h1> Search here </h1>
<%= form_tag('/flights#index', method: "get") do %>  	  
  	  <%= label_tag :starting_airport %>
  	  <%= select_tag :starting_airport, options_for_select(@airport_codes) %>
  	  <%= label_tag :finishing_airport %>
  	  <%= select_tag :finishing_airport, options_for_select(@airport_codes) %>
  	  <%= label_tag :start_date_time %>
  	  <%= select_tag :start_date_time, options_for_select(@dates) %>
      <%= label_tag :passengers %>
      <%= select_tag :passengers, options_for_select([1, 2, 3, 4]) %>
      <%= submit_tag "Search" %>
<% end %>

<% if @searched_flights != [] %>
  <h2> Search Results </h2>
  <%= form_tag('/bookings/new', method: "get") do %>
  	<% @searched_flights.each do |flight| %>
      <br>
      <div style ="height: 280px; width: 400px; border:1px solid black">
        <h3> Flight Details <%= radio_button_tag(:chosen_flight_id, flight.id) %> </h3>
        <h4>Departure: <%= flight.starting_airport.code %> </h4>
        <p>Date: <%= print_date(flight.start_date_time) %> Time: <%= print_time(flight.start_date_time) %></p>
        <p>Duration: <%= flight.duration_seconds %></p>
        <h4>Arrival: <%= flight.finishing_airport.code %> </h4>
        <p>Date: <%= print_date(flight.start_date_time + flight.duration_seconds) %> Time: <%= print_time(flight.start_date_time + flight.duration_seconds) %></p>
      </div>
  	<%end%>
    <%= hidden_field_tag :passengers, params[:passengers] %>
    <%= submit_tag "Select"%>
  <%end%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>